//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace User_Registration_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SleepTemporary
    {
        public int TemporarySleepId { get; set; }
        public System.DateTime StartSleep { get; set; }
        public Nullable<int> EveningRating { get; set; }
        public Nullable<int> MorningRating { get; set; }
        public Nullable<bool> QuickSleep { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
